package com.example.trivial.model

object QuestionProvider {
    val listaDePreguntas = listOf(

        //Geografia facil
        QuestionModel("¿Cuál es la capital de Francia?", listOf("Madrid", "Paris", "Londres", "Pepe"), "Paris", "Geografía", "Fácil"),
        QuestionModel("¿Cuál es la capital de Japón?", listOf("Pekín", "Seúl", "Tokio", "Bangkok"), "Tokio", "Geografía", "Fácil"),
        QuestionModel("¿En qué continente se encuentra el río Amazonas?", listOf("África", "América del Sur", "Asia", "Europa"), "América del Sur", "Geografía", "Fácil"),
        QuestionModel("¿Cuál es el país más grande del mundo en términos de superficie?", listOf("Estados Unidos", "Rusia", "China", "Brasil"), "Rusia", "Geografía", "Fácil"),
        QuestionModel("¿Cuál es la cordillera más larga del mundo?", listOf("Montañas Rocosas", "Himalaya", "Andes", "Alpes"), "Andes", "Geografía", "Fácil"),
        QuestionModel("¿En qué país se encuentra la Gran Barrera de Coral?", listOf("Australia", "Brasil", "México", "Sudáfrica"), "Australia", "Geografía", "Fácil"),
        QuestionModel("¿Cuál es la capital de Italia?", listOf("Madrid", "Roma", "Atenas", "Lisboa"), "Roma", "Geografía", "Fácil"),
        QuestionModel("¿Cuál es el punto más alto de la Tierra?", listOf("Mont Everest", "Mont McKinley", "Kilimanjaro", "Aconcagua"), "Mont Everest", "Geografía", "Fácil"),
        QuestionModel("¿En qué océano se encuentra la isla de Madagascar?", listOf("Océano Atlántico", "Océano Índico", "Océano Pacífico", "Mar Mediterráneo"), "Océano Índico", "Geografía", "Fácil"),
        QuestionModel("¿Cuál es el desierto más grande del mundo?", listOf("Desierto del Sahara", "Desierto de Atacama", "Desierto de Gobi", "Desierto de Kalahari"), "Desierto del Sahara", "Geografía", "Fácil"),
        QuestionModel("¿Cuál es el río más largo del mundo?", listOf("Nilo", "Amazonas", "Yangtsé", "Misisipi"), "Amazonas", "Geografía", "Fácil"),
        QuestionModel("¿En qué continente se encuentra el desierto del Sahara?", listOf("África", "Asia", "América", "Europa"), "África", "Geografía", "Fácil"),
        QuestionModel("¿Cuál es la capital de Canadá?", listOf("Ottawa", "Toronto", "Montreal", "Vancouver"), "Ottawa", "Geografía", "Fácil"),
        QuestionModel("¿Cuál es la montaña más alta del mundo?", listOf("Monte Everest", "Monte Kilimanjaro", "Monte McKinley", "Monte Aconcagua"), "Monte Everest", "Geografía", "Fácil"),
        QuestionModel("¿En qué país se encuentra la Gran Barrera de Coral?", listOf("Australia", "Brasil", "México", "India"), "Australia", "Geografía", "Fácil"),
        QuestionModel("¿Cuál es el océano más grande del mundo?", listOf("Océano Pacífico", "Océano Atlántico", "Océano Índico", "Océano Antártico"), "Océano Pacífico", "Geografía", "Fácil"),
        QuestionModel("¿Cuál es la capital de Corea del sur?", listOf("Tokio", "Pekín", "Seúl", "Bangkok"), "Seúl", "Geografía", "Fácil"),
        QuestionModel("¿En qué país se encuentra la Torre Eiffel?", listOf("Francia", "Italia", "Alemania", "Reino Unido"), "Francia", "Geografía", "Fácil"),
        QuestionModel("¿Cuál es el lago más grande de América del Norte?", listOf("Lago Superior", "Lago Hurón", "Lago Míchigan", "Lago Ontario"), "Lago Superior", "Geografía", "Fácil"),
        QuestionModel("¿En qué continente se encuentra la selva amazónica?", listOf("América del Sur", "África", "Asia", "Oceanía"), "América del Sur", "Geografía", "Fácil"),


        //Historia facil
        QuestionModel("¿Quién fue el primer presidente de Estados Unidos?", listOf("George Washington", "Thomas Jefferson", "Abraham Lincoln", "Pedro Sanchez"), "George Washington", "Historia", "Medio"),
        QuestionModel("¿Quién fue el líder de la Revolución Rusa en 1917?", listOf("Vladimir Lenin", "Joseph Stalin", "Leon Trotsky", "Mikhail Gorbachev"), "Vladimir Lenin", "Historia", "Fácil"),
        QuestionModel("¿En qué año finalizó la Segunda Guerra Mundial?", listOf("1943", "1945", "1947", "1950"), "1945", "Historia", "Fácil"),
        QuestionModel("¿Quién fue el primer presidente de Estados Unidos?", listOf("Thomas Jefferson", "George Washington", "John Adams", "James Madison"), "George Washington", "Historia", "Fácil"),
        QuestionModel("¿Cuál fue el evento que marcó el inicio de la Revolución Francesa en 1789?", listOf("La Toma de la Bastilla", "La Batalla de Waterloo", "La Marcha de Versalles", "El Asalto a la Conciergerie"), "La Toma de la Bastilla", "Historia", "Fácil"),
        QuestionModel("¿Quién fue el líder de la independencia de la India en la década de 1940?", listOf("Jawaharlal Nehru", "Mahatma Gandhi", "Indira Gandhi", "Sardar Patel"), "Mahatma Gandhi", "Historia", "Fácil"),
        QuestionModel("¿Qué evento histórico marcó el final de la Guerra Fría?", listOf("Caída del Muro de Berlín", "Crisis de los Misiles en Cuba", "Revolución Cubana", "Invasión de Normandía"), "Caída del Muro de Berlín", "Historia", "Fácil"),
        QuestionModel("¿En qué año se firmó la Declaración de Independencia de los Estados Unidos?", listOf("1776", "1789", "1792", "1804"), "1776", "Historia", "Fácil"),
        QuestionModel("¿Quién fue el líder de la Revolución China en 1949?", listOf("Chiang Kai-shek", "Sun Yat-sen", "Mao Zedong", "Deng Xiaoping"), "Mao Zedong", "Historia", "Fácil"),
        QuestionModel("¿Cuál fue el tratado que puso fin a la Primera Guerra Mundial?", listOf("Tratado de Versalles", "Tratado de Trianon", "Tratado de Brest-Litovsk", "Tratado de Saint-Germain-en-Laye"), "Tratado de Versalles", "Historia", "Fácil"),
        QuestionModel("¿En qué año se firmó la Declaración de Independencia de los Estados Unidos?", listOf("1776", "1789", "1792", "1804"), "1776", "Historia", "Fácil"),
        QuestionModel("¿Quién fue el primer presidente de los Estados Unidos?", listOf("George Washington", "Thomas Jefferson", "John Adams", "James Madison"), "George Washington", "Historia", "Fácil"),
        QuestionModel("¿Cuál fue la civilización que construyó las pirámides de Giza en Egipto?", listOf("Antiguo Egipto", "Mesopotamia", "Grecia Antigua", "Imperio Romano"), "Antiguo Egipto", "Historia", "Fácil"),
        QuestionModel("¿En qué año comenzó la Primera Guerra Mundial?", listOf("1914", "1918", "1922", "1939"), "1914", "Historia", "Fácil"),
        QuestionModel("¿Quién fue el líder de la Revolución Rusa de 1917?", listOf("Vladimir Lenin", "Joseph Stalin", "Leon Trotsky", "Nicholas II"), "Vladimir Lenin", "Historia", "Fácil"),
        QuestionModel("¿Cuál fue el evento que marcó el comienzo de la Revolución Americana en 1775?", listOf("Batalla de Lexington y Concord", "Batalla de Saratoga", "Declaración de Independencia", "Tratado de París"), "Batalla de Lexington y Concord", "Historia", "Fácil"),
        QuestionModel("¿En qué año finalizó la Segunda Guerra Mundial?", listOf("1945", "1940", "1942", "1948"), "1945", "Historia", "Fácil"),
        QuestionModel("¿En qué siglo tuvo lugar la Revolución Industrial?", listOf("Siglo XIX", "Siglo XVIII", "Siglo XX", "Siglo XVII"), "Siglo XIX", "Historia", "Fácil"),
        QuestionModel("¿Cuál fue el tratado que puso fin a la Primera Guerra Mundial en 1919?", listOf("Tratado de Versalles", "Tratado de Trianón", "Tratado de Brest-Litovsk", "Tratado de Saint-Germain"), "Tratado de Versalles", "Historia", "Fácil"),


        //Deportes facil
        QuestionModel("¿En qué deporte se puntúa a través de encestes en una canasta?", listOf("Fútbol", "Baloncesto", "Tenis", "Golf"), "Baloncesto", "Deportes", "Fácil"),
        QuestionModel("¿Cuál es el deporte más popular en Brasil?", listOf("Fútbol", "Voleibol", "Tenis", "Baloncesto"), "Fútbol", "Deportes", "Fácil"),
        QuestionModel("¿Cuál es el evento deportivo internacional que se celebra cada cuatro años y reúne a atletas de todo el mundo?", listOf("Copa Mundial de la FIFA", "Juegos Olímpicos", "Copa Davis", "Super Bowl"), "Juegos Olímpicos", "Deportes", "Fácil"),
        QuestionModel("¿En qué deporte se utiliza una raqueta para golpear una pelota sobre una red?", listOf("Golf", "Tenis", "Bádminton", "Ping Pong"), "Tenis", "Deportes", "Fácil"),
        QuestionModel("¿Cuál es el deporte acuático en el que los participantes montan sobre una tabla y son arrastrados por una embarcación motorizada?", listOf("Surf", "Esquí acuático", "Windsurf", "Kitesurf"), "Esquí acuático", "Deportes", "Fácil"),
        QuestionModel("¿En qué deporte se utiliza un guante y una pelota, y se juega en un diamante con bases?", listOf("Baloncesto", "Béisbol", "Softbol", "Críquet"), "Béisbol", "Deportes", "Fácil"),
        QuestionModel("¿Cuál es el deporte en el que los competidores deben nadar, andar en bicicleta y correr en una secuencia continua?", listOf("Atletismo", "Triatlón", "Pentatlón", "Duatlón"), "Triatlón", "Deportes", "Fácil"),
        QuestionModel("¿En qué deporte se utiliza un palo para golpear una pelota hacia un hoyo en el menor número de golpes posible?", listOf("Tenis", "Golf", "Críquet", "Hockey"), "Golf", "Deportes", "Fácil"),
        QuestionModel("¿Cuál es el deporte en el que los jugadores compiten por anotar puntos al lanzar una pelota a través de un aro?", listOf("Balonmano", "Rugby", "Baloncesto", "Hockey"), "Baloncesto", "Deportes", "Fácil"),
        QuestionModel("¿En qué deporte los jugadores compiten para golpear una pelota blanca con un palo y colocarla en un hoyo en el menor número de golpes posible?", listOf("Golf", "Bádminton", "Tenis de mesa", "Croquet"), "Golf", "Deportes", "Fácil"),
        QuestionModel("¿En qué deporte se juega la Copa Davis?", listOf("Tenis", "Fútbol", "Golf", "Baloncesto"), "Tenis", "Deportes", "Fácil"),
        QuestionModel("¿Cuál es el evento deportivo que se celebra cada cuatro años y reúne a atletas de todo el mundo?", listOf("Juegos Olímpicos", "Copa Mundial de Fútbol", "Super Bowl", "Copa del Mundo de Rugby"), "Juegos Olímpicos", "Deportes", "Fácil"),
        QuestionModel("¿Cuántos jugadores hay en un equipo de fútbol en el campo durante un partido?", listOf("11", "10", "9", "12"), "11", "Deportes", "Fácil"),
        QuestionModel("¿En qué deporte se utiliza una red y una pelota con plumas?", listOf("Bádminton", "Vóley", "Tenis de mesa", "Squash"), "Bádminton", "Deportes", "Fácil"),
        QuestionModel("¿Cuál es el deporte conocido como el 'deporte rey'?", listOf("Fútbol", "Tenis", "Baloncesto", "Golf"), "Fútbol", "Deportes", "Fácil"),
        QuestionModel("¿En qué deporte se realiza la competición llamada 'Tour de Francia'?", listOf("Ciclismo", "Atletismo", "Esquí", "Natación"), "Ciclismo", "Deportes", "Fácil"),
        QuestionModel("¿Cuál es el nombre del torneo de tenis que se juega en césped y es el más antiguo del mundo?", listOf("Wimbledon", "Roland Garros", "US Open", "Australian Open"), "Wimbledon", "Deportes", "Fácil"),
        QuestionModel("¿Cuál es el nombre del trofeo otorgado al campeón de la NFL en Estados Unidos?", listOf("Trofeo Vince Lombardi", "Copa Stanley", "Trofeo Lombardo", "Bowl de Super"), "Trofeo Vince Lombardi", "Deportes", "Fácil"),
        QuestionModel("¿Cuál es el deporte que se juega en una pista dividida en carriles y consiste en lanzar una bola hacia un conjunto de bolos?", listOf("Bolos", "Críquet", "Béisbol", "Golf"), "Bolos", "Deportes", "Fácil"),
        QuestionModel("¿En qué deporte se utiliza una pala para golpear una pelota sobre una red?", listOf("Pádel", "Tenis", "Squash", "Bádminton"), "Pádel", "Deportes", "Fácil"),


        //Arte y literatura facil
        QuestionModel("¿Quién pintó la Mona Lisa?", listOf("Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"), "Leonardo da Vinci", "Arte y literatura", "Fácil"),
        QuestionModel("¿Quién escribió 'Don Quijote de la Mancha'?", listOf("Miguel de Cervantes", "Gabriel García Márquez", "William Shakespeare", "Federico García Lorca"), "Miguel de Cervantes", "Arte y literatura", "Fácil"),
        QuestionModel("¿Cuál es la obra más conocida de William Shakespeare?", listOf("Romeo y Julieta", "Hamlet", "Macbeth", "Otelo"), "Romeo y Julieta", "Arte y literatura", "Fácil"),
        QuestionModel("¿Quién es conocido como el pintor del 'Guernica'?", listOf("Pablo Picasso", "Salvador Dalí", "Claude Monet", "Vincent van Gogh"), "Pablo Picasso", "Arte y literatura", "Fácil"),
        QuestionModel("¿Qué famoso pintor neerlandés cortó su propio oído?", listOf("Vincent van Gogh", "Rembrandt", "Johannes Vermeer", "Hieronymus Bosch"), "Vincent van Gogh", "Arte y literatura", "Fácil"),
        QuestionModel("¿Quién escribió 'Cien años de soledad'?", listOf("Gabriel García Márquez", "Mario Vargas Llosa", "Isabel Allende", "Julio Cortázar"), "Gabriel García Márquez", "Arte y literatura", "Fácil"),
        QuestionModel("¿Cuál es la técnica artística que utiliza la mezcla de colores mediante pequeños puntos?", listOf("Cubismo", "Puntillismo", "Impresionismo", "Expresionismo"), "Puntillismo", "Arte y literatura", "Fácil"),
        QuestionModel("¿Quién fue el autor de 'La noche estrellada'?", listOf("Vincent van Gogh", "Claude Monet", "Pablo Picasso", "Salvador Dalí"), "Vincent van Gogh", "Arte y literatura", "Fácil"),
        QuestionModel("¿Qué famoso dramaturgo inglés escribió 'Romeo y Julieta'?", listOf("Christopher Marlowe", "Ben Jonson", "William Shakespeare", "John Milton"), "William Shakespeare", "Arte y literatura", "Fácil"),
        QuestionModel("¿En qué periodo artístico se destacó Leonardo da Vinci?", listOf("Renacimiento", "Barroco", "Romanticismo", "Impresionismo"), "Renacimiento", "Arte y literatura", "Fácil"),
        QuestionModel("¿En qué país nació el pintor surrealista Salvador Dalí?", listOf("España", "Francia", "Italia", "Bélgica"), "España", "Arte y literatura", "Fácil"),
        QuestionModel("¿Quién pintó la Mona Lisa?", listOf("Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Claude Monet"), "Leonardo da Vinci", "Arte y literatura", "Fácil"),
        QuestionModel("¿Cuál es la obra más famosa de William Shakespeare?", listOf("Romeo y Julieta", "Hamlet", "Macbeth", "Otelo"), "Romeo y Julieta", "Arte y literatura", "Fácil"),
        QuestionModel("¿Quién escribió 'Cien años de soledad'?", listOf("Gabriel García Márquez", "Julio Cortázar", "Mario Vargas Llosa", "Isabel Allende"), "Gabriel García Márquez", "Arte y literatura", "Fácil"),
        QuestionModel("¿Cuál es el nombre del movimiento artístico caracterizado por el uso de colores vibrantes y pinceladas cortas?", listOf("Impresionismo", "Cubismo", "Fauvismo", "Realismo"), "Impresionismo", "Arte y literatura", "Fácil"),
        QuestionModel("¿Quién es el autor de la novela 'Don Quijote de la Mancha'?", listOf("Miguel de Cervantes", "Federico García Lorca", "Jorge Luis Borges", "Garcilaso de la Vega"), "Miguel de Cervantes", "Arte y literatura", "Fácil"),
        QuestionModel("¿Cuál es el nombre del movimiento artístico que utiliza elementos visuales ilusorios para engañar al espectador?", listOf("Op Art", "Surrealismo", "Cubismo", "Fauvismo"), "Op Art", "Arte y literatura", "Fácil"),
        QuestionModel("¿Quién escribió la novela 'Orgullo y prejuicio'?", listOf("Jane Austen", "Charlotte Brontë", "Emily Brontë", "Charles Dickens"), "Jane Austen", "Arte y literatura", "Fácil"),
        QuestionModel("¿Cuál es el nombre del cuadro famoso que representa a una mujer con un enigmático gesto de sonrisa?", listOf("La Gioconda", "La Noche Estrellada", "Guernica", "Los Girasoles"), "La Gioconda", "Arte y literatura", "Fácil"),
        QuestionModel("¿Quién es conocido por sus esculturas de figuras musculosas y perfectamente proporcionadas, como 'David'?", listOf("Michelangelo Buonarroti", "Leonardo da Vinci", "Donatello", "Raphael Sanzio"), "Michelangelo Buonarroti", "Arte y literatura", "Fácil"),
        QuestionModel("¿Cuál es el género literario de 'Drácula', escrito por Bram Stoker?", listOf("Novela de Terror", "Ciencia Ficción", "Romance", "Novela Histórica"), "Novela de Terror", "Arte y literatura", "Fácil"),



        //Entretenimiento facil
        QuestionModel("¿Quién fue el director de Matrix?", listOf("Lana Wachowski", "Monica Blanchette", "Harry Styles", "Silvester Stallone"), "Lana Wachowski", "Entretenimiento", "Facil"),
        QuestionModel("¿Quién interpretó a Harry Potter en la serie de películas basadas en los libros de J.K. Rowling?", listOf("Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Tom Felton"), "Daniel Radcliffe", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es la película ganadora del Oscar a la Mejor Película en 1994, dirigida por Robert Zemeckis y protagonizada por Tom Hanks?", listOf("Forrest Gump", "Titanic", "Braveheart", "Schindler's List"), "Forrest Gump", "Entretenimiento", "Fácil"),
        QuestionModel("¿Qué popular serie de televisión se desarrolla en el ficticio continente de Westeros?", listOf("Breaking Bad", "Stranger Things", "Game of Thrones", "The Walking Dead"), "Game of Thrones", "Entretenimiento", "Fácil"),
        QuestionModel("¿Quién es el director de la trilogía 'El Señor de los Anillos'?", listOf("Christopher Nolan", "Peter Jackson", "Steven Spielberg", "George Lucas"), "Peter Jackson", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es el nombre del robot amigable que aparece en la película de animación 'Wall-E' de Pixar?", listOf("R2-D2", "EVA", "C-3PO", "Wall-E"), "Wall-E", "Entretenimiento", "Fácil"),
        QuestionModel("¿Quién es el creador de la serie de televisión 'Friends'?", listOf("J.J. Abrams", "David Crane", "Aaron Sorkin", "David Schwimmer"), "David Crane", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es la película que presenta a un joven león llamado Simba y es conocida por su icónica canción 'El Ciclo de la Vida'?", listOf("Mulan", "The Lion King", "Aladdin", "Beauty and the Beast"), "The Lion King", "Entretenimiento", "Fácil"),
        QuestionModel("¿Qué actor interpreta a Tony Stark en la saga de películas de Marvel conocida como 'Iron Man'?", listOf("Chris Hemsworth", "Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"), "Robert Downey Jr.", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es el nombre del protagonista de la serie de televisión 'Breaking Bad'?", listOf("Walter White", "Jesse Pinkman", "Saul Goodman", "Hank Schrader"), "Walter White", "Entretenimiento", "Fácil"),
        QuestionModel("¿Qué director fue responsable de la trilogía de 'El Caballero de la Noche' en la franquicia de Batman?", listOf("Tim Burton", "Christopher Nolan", "Zack Snyder", "Joss Whedon"), "Christopher Nolan", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es la película animada de Disney sobre un león que enfrenta desafíos para reclamar su lugar como rey de la sabana?", listOf("El Rey León", "Aladdin", "La Sirenita", "Mulan"), "El Rey León", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es el nombre del personaje principal en la serie de libros 'Harry Potter'?", listOf("Harry Potter", "Ron Weasley", "Hermione Granger", "Albus Dumbledore"), "Harry Potter", "Entretenimiento", "Fácil"),
        QuestionModel("¿Quién es conocido como el 'Rey del Pop'?", listOf("Michael Jackson", "Elvis Presley", "Prince", "David Bowie"), "Michael Jackson", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es la serie de televisión que sigue las vidas de los personajes en el pueblo de Springfield?", listOf("Los Simpson", "Padre de Familia", "Bob Esponja", "South Park"), "Los Simpson", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es el nombre del mago ficticio creado por J.K. Rowling que es director de la escuela Hogwarts?", listOf("Albus Dumbledore", "Severus Snape", "Rubeus Hagrid", "Gellert Grindelwald"), "Albus Dumbledore", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es el nombre del famoso agente secreto británico creado por Ian Fleming?", listOf("James Bond", "Jason Bourne", "Ethan Hunt", "Jack Ryan"), "James Bond", "Entretenimiento", "Fácil"),
        QuestionModel("¿En qué película protagonizada por Tom Hanks un hombre queda atrapado en una isla desierta con una pelota llamada Wilson?", listOf("Náufrago", "Forrest Gump", "El Código Da Vinci", "El Resplandor"), "Náufrago", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es el título de la serie de libros de fantasía escrita por J.R.R. Tolkien que incluye 'El Señor de los Anillos'?", listOf("La Tierra Media", "Canción de Hielo y Fuego", "Narnia", "Harry Potter"), "La Tierra Media", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es el nombre del director y creador de la saga cinematográfica 'Star Wars'?", listOf("George Lucas", "Steven Spielberg", "James Cameron", "Christopher Nolan"), "George Lucas", "Entretenimiento", "Fácil"),
        QuestionModel("¿En qué ciudad ficticia se desarrolla la serie de televisión 'Friends'?", listOf("Nueva York", "Los Ángeles", "Chicago", "Miami"), "Nueva York", "Entretenimiento", "Fácil"),




        //Geografia medio
        QuestionModel("¿Cuál es la capital de Sudáfrica?", listOf("Pretoria", "Ciudad del Cabo", "Bloemfontein", "Johannesburgo"), "Pretoria", "Geografía", "Medio"),
        QuestionModel("¿En qué océano se encuentra la isla de Tasmania?", listOf("Océano Pacífico", "Océano Atlántico", "Mar de Tasmania", "Océano Índico"), "Océano Índico", "Geografía", "Medio"),
        QuestionModel("¿Cuál es el río más largo de América del Norte?", listOf("Río Misisipi", "Río Yukón", "Río Columbia", "Río Missouri"), "Río Missouri", "Geografía", "Medio"),
        QuestionModel("¿En qué país se encuentra el monte Kilimanjaro?", listOf("Kenia", "Tanzania", "Uganda", "Ruanda"), "Tanzania", "Geografía", "Medio"),
        QuestionModel("¿Cuál es la capital de Turquía?", listOf("Estambul", "Ankara", "Izmir", "Adana"), "Ankara", "Geografía", "Medio"),
        QuestionModel("¿Cuál es el punto más bajo de la Tierra?", listOf("Gran Barrera de Coral", "Depresión de Afar", "Mar Muerto", "Cañón del Colorado"), "Mar Muerto", "Geografía", "Medio"),
        QuestionModel("¿En qué continente se encuentra la Cordillera de los Andes?", listOf("Asia", "Europa", "América del Sur", "África"), "América del Sur", "Geografía", "Medio"),
        QuestionModel("¿Cuál es el estrecho que separa Europa de África?", listOf("Estrecho de Gibraltar", "Estrecho de Bering", "Estrecho de Malaca", "Estrecho de Ormuz"), "Estrecho de Gibraltar", "Geografía", "Medio"),
        QuestionModel("¿En qué país se encuentra el desierto de Mojave?", listOf("Estados Unidos", "México", "Canadá", "Australia"), "Estados Unidos", "Geografía", "Medio"),
        QuestionModel("¿Cuál es el país más poblado del mundo?", listOf("India", "Estados Unidos", "China", "Brasil"), "China", "Geografía", "Medio"),
        QuestionModel("¿Cuál es la película animada de Disney sobre un león que enfrenta desafíos para reclamar su lugar como rey de la sabana?", listOf("El Rey León", "Aladdin", "La Sirenita", "Mulan"), "El Rey León", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es el nombre del personaje principal en la serie de libros 'Harry Potter'?", listOf("Harry Potter", "Ron Weasley", "Hermione Granger", "Albus Dumbledore"), "Harry Potter", "Entretenimiento", "Fácil"),
        QuestionModel("¿Quién es conocido como el 'Rey del Pop'?", listOf("Michael Jackson", "Elvis Presley", "Prince", "David Bowie"), "Michael Jackson", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es la serie de televisión que sigue las vidas de los personajes en el pueblo de Springfield?", listOf("Los Simpson", "Padre de Familia", "Bob Esponja", "South Park"), "Los Simpson", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es el nombre del mago ficticio creado por J.K. Rowling que es director de la escuela Hogwarts?", listOf("Albus Dumbledore", "Severus Snape", "Rubeus Hagrid", "Gellert Grindelwald"), "Albus Dumbledore", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es el nombre del famoso agente secreto británico creado por Ian Fleming?", listOf("James Bond", "Jason Bourne", "Ethan Hunt", "Jack Ryan"), "James Bond", "Entretenimiento", "Fácil"),
        QuestionModel("¿En qué película protagonizada por Tom Hanks un hombre queda atrapado en una isla desierta con una pelota llamada Wilson?", listOf("Náufrago", "Forrest Gump", "El Código Da Vinci", "El Resplandor"), "Náufrago", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es el título de la serie de libros de fantasía escrita por J.R.R. Tolkien que incluye 'El Señor de los Anillos'?", listOf("La Tierra Media", "Canción de Hielo y Fuego", "Narnia", "Harry Potter"), "La Tierra Media", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es el nombre del director y creador de la saga cinematográfica 'Star Wars'?", listOf("George Lucas", "Steven Spielberg", "James Cameron", "Christopher Nolan"), "George Lucas", "Entretenimiento", "Fácil"),
        QuestionModel("¿En qué ciudad ficticia se desarrolla la serie de televisión 'Friends'?", listOf("Nueva York", "Los Ángeles", "Chicago", "Miami"), "Nueva York", "Entretenimiento", "Fácil"),
        QuestionModel("¿Cuál es la capital de Sudáfrica?", listOf("Pretoria", "Ciudad del Cabo", "Bloemfontein", "Johannesburgo"), "Pretoria", "Geografía", "Medio"),
        QuestionModel("¿En qué país se encuentra el río Danubio?", listOf("Europa", "Asia", "África", "América"), "Europa", "Geografía", "Medio"),
        QuestionModel("¿Cuál es la ciudad más poblada de Brasil?", listOf("São Paulo", "Río de Janeiro", "Brasilia", "Salvador"), "São Paulo", "Geografía", "Medio"),
        QuestionModel("¿En qué cordillera se encuentra la montaña más alta de Norteamérica, el Monte McKinley?", listOf("Montañas de Alaska", "Montañas Rocosas", "Montañas Apalaches", "Sierra Nevada"), "Montañas de Alaska", "Geografía", "Medio"),
        QuestionModel("¿Cuál es la capital de Canadá?", listOf("Ottawa", "Toronto", "Vancouver", "Montreal"), "Ottawa", "Geografía", "Medio"),
        QuestionModel("¿Cuál es el país más grande del mundo por área terrestre?", listOf("Rusia", "Canadá", "Estados Unidos", "China"), "Rusia", "Geografía", "Medio"),
        QuestionModel("¿En qué océano se encuentra la isla de Madagascar?", listOf("Océano Índico", "Océano Atlántico", "Océano Pacífico", "Mar Mediterráneo"), "Océano Índico", "Geografía", "Medio"),
        QuestionModel("¿Cuál es la capital de Suecia?", listOf("Estocolmo", "Oslo", "Copenhague", "Helsinki"), "Estocolmo", "Geografía", "Medio"),
        QuestionModel("¿En qué país se encuentra el desierto de Gobi?", listOf("Mongolia", "China", "India", "Kazajistán"), "Mongolia", "Geografía", "Medio"),
        QuestionModel("¿Cuál es la cadena montañosa que separa Europa de Asia?", listOf("Montes Urales", "Montañas de los Cárpatos", "Montañas del Cáucaso", "Montañas Pirin"), "Montes Urales", "Geografía", "Medio"),


        //Historia medio
        QuestionModel("¿En qué año ocurrió la Revolución Rusa?", listOf("1917", "1923", "1905", "1939"), "1917", "Historia", "Medio"),
        QuestionModel("¿Quién fue el presidente de Estados Unidos durante la Guerra Civil Americana?", listOf("Abraham Lincoln", "Andrew Johnson", "Ulysses S. Grant", "James Buchanan"), "Abraham Lincoln", "Historia", "Medio"),
        QuestionModel("¿Qué líder político y militar francés lideró las fuerzas aliadas en la Batalla de Waterloo?", listOf("Napoleón Bonaparte", "Louis XIV", "Charles de Gaulle", "Louis Napoleon"), "Napoleón Bonaparte", "Historia", "Medio"),
        QuestionModel("¿Cuándo ocurrió la Revolución Industrial?", listOf("Siglo XVIII", "Siglo XIX", "Siglo XX", "Siglo XVII"), "Siglo XVIII", "Historia", "Medio"),
        QuestionModel("¿Cuál fue la causa principal de la Guerra de los Cien Años?", listOf("Disputa por el trono inglés", "Disputa por el trono francés", "Disputa por el trono español", "Disputa por el trono alemán"), "Disputa por el trono francés", "Historia", "Medio"),
        QuestionModel("¿Qué tratado puso fin a la Primera Guerra Mundial?", listOf("Tratado de Versalles", "Tratado de Trianon", "Tratado de Brest-Litovsk", "Tratado de Saint-Germain-en-Laye"), "Tratado de Versalles", "Historia", "Medio"),
        QuestionModel("¿Quién fue la Reina de Egipto conocida por su relación con Marco Antonio y Julio César?", listOf("Cleopatra", "Nefertiti", "Hatshepsut", "Isis"), "Cleopatra", "Historia", "Medio"),
        QuestionModel("¿Qué evento marcó el comienzo de la Segunda Guerra Mundial?", listOf("Invasión de Polonia", "Batalla de Stalingrado", "Ataque a Pearl Harbor", "Invasión de Normandía"), "Invasión de Polonia", "Historia", "Medio"),
        QuestionModel("¿Cuándo ocurrió la Revolución China liderada por Mao Zedong?", listOf("1911", "1949", "1928", "1936"), "1949", "Historia", "Medio"),
        QuestionModel("¿Quién fue el líder de la Revolución Cubana en 1959?", listOf("Fidel Castro", "Che Guevara", "Batista", "Camilo Cienfuegos"), "Fidel Castro", "Historia", "Medio"),
        QuestionModel("¿En qué año comenzó la Revolución Industrial en Inglaterra?", listOf("Siglo XVIII", "Siglo XIX", "Siglo XVII", "Siglo XVI"), "Siglo XVIII", "Historia", "Medio"),
        QuestionModel("¿Quién fue el emperador romano conocido por su código legal y por expandir el Imperio Romano a su máxima extensión territorial?", listOf("Justiniano I", "César Augusto", "Marco Aurelio", "Trajano"), "Justiniano I", "Historia", "Medio"),
        QuestionModel("¿En qué año se llevó a cabo la Revolución Francesa?", listOf("1789", "1799", "1804", "1815"), "1789", "Historia", "Medio"),
        QuestionModel("¿Cuál fue la dinastía que gobernó China durante la Edad de Oro de la cultura china, conocida por la construcción de la Gran Muralla?", listOf("Dinastía Han", "Dinastía Tang", "Dinastía Ming", "Dinastía Qing"), "Dinastía Ming", "Historia", "Medio"),
        QuestionModel("¿En qué año se firmó el Tratado de Versalles, poniendo fin a la Primera Guerra Mundial?", listOf("1919", "1918", "1920", "1921"), "1919", "Historia", "Medio"),
        QuestionModel("¿Quién fue el líder de la Revolución Rusa que posteriormente se convirtió en el primer líder de la Unión Soviética?", listOf("Vladimir Lenin", "Joseph Stalin", "Leon Trotsky", "Nikita Jrushchov"), "Vladimir Lenin", "Historia", "Medio"),
        QuestionModel("¿Cuál fue la principal causa del inicio de la Guerra de Secesión en Estados Unidos?", listOf("Esclavitud", "Diferencias económicas", "Derechos estatales", "Impuestos"), "Esclavitud", "Historia", "Medio"),
        QuestionModel("¿En qué año se llevó a cabo la Revolución Industrial en Estados Unidos?", listOf("Siglo XIX", "Siglo XVIII", "Siglo XX", "Siglo XVII"), "Siglo XIX", "Historia", "Medio"),
        QuestionModel("¿Cuál fue el conflicto bélico que enfrentó a Estados Unidos y la Unión Soviética durante la Guerra Fría sin un enfrentamiento militar directo?", listOf("Guerra Fría", "Carrera Espacial", "Crisis de los Misiles en Cuba", "Guerra de Vietnam"), "Guerra Fría", "Historia", "Medio"),
        QuestionModel("¿En qué año se llevó a cabo la Revolución Mexicana?", listOf("1910", "1920", "1900", "1930"), "1910", "Historia", "Medio"),

        //Deportes Medio
        QuestionModel("¿En qué deporte se utiliza una pala para golpear una pelota sobre una mesa dividida por una red?", listOf("Tenis de mesa", "Paddle", "Bádminton", "Squash"), "Tenis de mesa", "Deportes", "Medio"),
        QuestionModel("¿Cuál es el máximo campeonato de fútbol a nivel de clubes en Europa?", listOf("Copa Sudamericana", "Copa Libertadores", "Liga de Campeones de la UEFA", "Europa League"), "Liga de Campeones de la UEFA", "Deportes", "Medio"),
        QuestionModel("¿En qué deporte se puntúa a través de encestes en una canasta?", listOf("Baloncesto", "Voleibol", "Rugby", "Hockey"), "Baloncesto", "Deportes", "Medio"),
        QuestionModel("¿Cuál es el equipo de fútbol más exitoso de Brasil?", listOf("Flamengo", "Santos", "Corinthians", "Palmeiras"), "Santos", "Deportes", "Medio"),
        QuestionModel("¿En qué deporte se compite por puntos realizando acrobacias en el aire?", listOf("Clavados", "Gimnasia rítmica", "Esquí acrobático", "Vóley playa"), "Clavados", "Deportes", "Medio"),
        QuestionModel("¿Cuál es el deporte en el que se compite por la posesión de un balón ovalado?", listOf("Fútbol Americano", "Rugby", "Críquet", "Hockey sobre hielo"), "Rugby", "Deportes", "Medio"),
        QuestionModel("¿En qué país se originó el judo?", listOf("Japón", "China", "Corea del Sur", "Rusia"), "Japón", "Deportes", "Medio"),
        QuestionModel("¿Cuál es el segundo Grand Slam de tenis en el año?", listOf("Roland Garros", "Wimbledon", "US Open", "Australian Open"), "Roland Garros", "Deportes", "Medio"),
        QuestionModel("¿Quién es conocido como 'El Rey' en el mundo del baloncesto?", listOf("Kobe Bryant", "LeBron James", "Michael Jordan", "Magic Johnson"), "Michael Jordan", "Deportes", "Medio"),
        QuestionModel("¿Cuál es el torneo de golf más prestigioso del mundo?", listOf("The Open Championship", "Masters de Augusta", "US Open", "PGA Championship"), "Masters de Augusta", "Deportes", "Medio"),
        QuestionModel("¿Cuál es el deporte de invierno que se juega deslizándose por una pista de hielo con una piedra y escobas?", listOf("Curling", "Bobsleigh", "Patinaje Artístico", "Hockey sobre hielo"), "Curling", "Deportes", "Medio"),
        QuestionModel("¿Cuántos jugadores conforman un equipo de balonmano en la cancha durante un partido?", listOf("7", "6", "5", "8"), "7", "Deportes", "Medio"),
        QuestionModel("¿En qué país se originó el deporte del judo?", listOf("Japón", "China", "Corea del Sur", "Rusia"), "Japón", "Deportes", "Medio"),
        QuestionModel("¿Cuál es el evento de ciclismo de ruta más famoso que se celebra anualmente en Francia?", listOf("Tour de Francia", "Giro de Italia", "Vuelta a España", "Paris-Roubaix"), "Tour de Francia", "Deportes", "Medio"),
        QuestionModel("¿En qué deporte se puntúa al anotar un 'try' y se juega con una pelota ovalada?", listOf("Rugby", "Fútbol Americano", "Críquet", "Hockey"), "Rugby", "Deportes", "Medio"),
        QuestionModel("¿Cuál es el equipo de fútbol español conocido como 'Los Merengues'?", listOf("Real Madrid", "Barcelona", "Atlético de Madrid", "Valencia"), "Real Madrid", "Deportes", "Medio"),
        QuestionModel("¿En qué deporte se utiliza una pala y una pelota perforada, similar al tenis?", listOf("Pickleball", "Pádel", "Ping Pong", "Squash"), "Pickleball", "Deportes", "Medio"),
        QuestionModel("¿Cuál es el país de origen del deporte del cricket?", listOf("Inglaterra", "India", "Australia", "Sudáfrica"), "Inglaterra", "Deportes", "Medio"),
        QuestionModel("¿En qué deporte se compite en una pista ovalada y se utiliza el término 'pelota rápida'?", listOf("Atletismo - Carreras de velocidad", "Béisbol", "Softbol", "Críquet"), "Atletismo - Carreras de velocidad", "Deportes", "Medio"),
        QuestionModel("¿Cuál es el torneo de tenis que se juega en superficie de arcilla y es uno de los cuatro Grand Slam?", listOf("Roland Garros", "Wimbledon", "US Open", "Australian Open"), "Roland Garros", "Deportes", "Medio"),

        //Arte y literatura medio

        QuestionModel("¿Quién pintó 'La Noche Estrellada'?", listOf("Vincent van Gogh", "Claude Monet", "Pablo Picasso", "Salvador Dalí"), "Vincent van Gogh", "Arte y literatura", "Medio"),
        QuestionModel("¿Quién escribió 'Orgullo y prejuicio'?", listOf("Charles Dickens", "Emily Brontë", "Jane Austen", "Leo Tolstoy"), "Jane Austen", "Arte y literatura", "Medio"),
        QuestionModel("¿Cuál es el movimiento artístico que se caracteriza por representar la realidad de manera precisa y detallada?", listOf("Impresionismo", "Expresionismo", "Realismo", "Cubismo"), "Realismo", "Arte y literatura", "Medio"),
        QuestionModel("¿Quién escribió 'Crimen y castigo'?", listOf("Fyodor Dostoevsky", "Leo Tolstoy", "Anton Chekhov", "Ivan Turgenev"), "Fyodor Dostoevsky", "Arte y literatura", "Medio"),
        QuestionModel("¿En qué país nació el pintor Pablo Picasso?", listOf("Italia", "España", "Francia", "Grecia"), "España", "Arte y literatura", "Medio"),
        QuestionModel("¿Quién es el autor de la obra teatral 'Romeo y Julieta'?", listOf("Christopher Marlowe", "William Shakespeare", "Ben Jonson", "John Milton"), "William Shakespeare", "Arte y literatura", "Medio"),
        QuestionModel("¿Qué pintor surrealista es conocido por sus relojes derretidos en obras como 'La persistencia de la memoria'?", listOf("René Magritte", "Salvador Dalí", "Joan Miró", "Max Ernst"), "Salvador Dalí", "Arte y literatura", "Medio"),
        QuestionModel("¿Cuál es la novela distópica escrita por George Orwell que describe un estado totalitario?", listOf("1984", "Un mundo feliz", "Fahrenheit 451", "Brave New World"), "1984", "Arte y literatura", "Medio"),
        QuestionModel("¿Quién es conocido por sus esculturas del David y La Piedad?", listOf("Michelangelo Buonarroti", "Leonardo da Vinci", "Donatello", "Raphael Sanzio"), "Michelangelo Buonarroti", "Arte y literatura", "Medio"),
        QuestionModel("¿Quién escribió 'Cien años de soledad'?", listOf("Gabriel García Márquez", "Mario Vargas Llosa", "Julio Cortázar", "Isabel Allende"), "Gabriel García Márquez", "Arte y literatura", "Medio"),
        QuestionModel("¿En qué país nació el pintor surrealista René Magritte?", listOf("Francia", "Bélgica", "Alemania", "Países Bajos"), "Bélgica", "Arte y literatura", "Medio"),
        QuestionModel("¿Cuál es el movimiento artístico caracterizado por la representación de la luz y el color de manera fragmentada?", listOf("Cubismo", "Impresionismo", "Fauvismo", "Realismo"), "Impresionismo", "Arte y literatura", "Medio"),
        QuestionModel("¿Quién es el autor de la obra 'Crimen en el Orient Express'?", listOf("Agatha Christie", "Arthur Conan Doyle", "Raymond Chandler", "Dashiell Hammett"), "Agatha Christie", "Arte y literatura", "Medio"),
        QuestionModel("¿Cuál de las siguientes obras es una pintura de Leonardo da Vinci?", listOf("El Grito", "La última cena", "Guernica", "Los girasoles"), "La última cena", "Arte y literatura", "Medio"),
        QuestionModel("¿Quién escribió 'Matar a un ruiseñor'?", listOf("Harper Lee", "John Steinbeck", "Mark Twain", "J.D. Salinger"), "Harper Lee", "Arte y literatura", "Medio"),
        QuestionModel("¿Cuál es el nombre de la corriente artística caracterizada por formas geométricas y colores primarios?", listOf("Cubismo", "Futurismo", "De Stijl", "Dadaísmo"), "De Stijl", "Arte y literatura", "Medio"),
        QuestionModel("¿Quién escribió 'El Gran Gatsby'?", listOf("F. Scott Fitzgerald", "Ernest Hemingway", "J.D. Salinger", "Sinclair Lewis"), "F. Scott Fitzgerald", "Arte y literatura", "Medio"),
        QuestionModel("¿Cuál es la técnica artística que utiliza la mezcla de colores mediante pequeños puntos?", listOf("Impresionismo", "Expresionismo", "Puntillismo", "Realismo"), "Puntillismo", "Arte y literatura", "Medio"),
        QuestionModel("¿Quién pintó 'El Jardín de las Delicias'?", listOf("Hieronymus Bosch", "Pieter Bruegel", "Jan van Eyck", "Hans Holbein"), "Hieronymus Bosch", "Arte y literatura", "Medio"),
        QuestionModel("¿Qué autor francés escribió 'Los Miserables'?", listOf("Gustave Flaubert", "Victor Hugo", "Émile Zola", "Albert Camus"), "Victor Hugo", "Arte y literatura", "Medio"),
        QuestionModel("¿Quién pintó 'La última cena'?", listOf("Leonardo da Vinci", "Michelangelo Buonarroti", "Vincent van Gogh", "Pablo Picasso"), "Leonardo da Vinci", "Arte y literatura", "Fácil"),


        //Entretenimiento medio
        QuestionModel("¿Cuál es el nombre del protagonista en la serie de televisión 'Breaking Bad'?", listOf("Walter White", "Jesse Pinkman", "Saul Goodman", "Hank Schrader"), "Walter White", "Entretenimiento", "Medio"),
        QuestionModel("¿En qué año se lanzó la primera temporada de la serie 'Stranger Things'?", listOf("2015", "2016", "2017", "2018"), "2016", "Entretenimiento", "Medio"),
        QuestionModel("¿Quién interpretó a Jack en la película 'Titanic'?", listOf("Leonardo DiCaprio", "Tom Hanks", "Brad Pitt", "Johnny Depp"), "Leonardo DiCaprio", "Entretenimiento", "Medio"),
        QuestionModel("¿Cuál es el nombre del actor que interpreta a Iron Man en las películas de Marvel?", listOf("Chris Hemsworth", "Chris Evans", "Robert Downey Jr.", "Mark Ruffalo"), "Robert Downey Jr.", "Entretenimiento", "Medio"),
        QuestionModel("¿En qué película el personaje principal lleva un traje de hierro y es conocido como Tony Stark?", listOf("Iron Man", "Captain America: The First Avenger", "Thor", "Guardians of the Galaxy"), "Iron Man", "Entretenimiento", "Medio"),
        QuestionModel("¿Cuál es el nombre del protagonista en la serie de televisión 'The Mandalorian'?", listOf("Luke Skywalker", "Han Solo", "Darth Vader", "The Mandalorian"), "The Mandalorian", "Entretenimiento", "Medio"),
        QuestionModel("¿Quién fue el creador de la serie de televisión 'Friends'?", listOf("David Crane", "J.J. Abrams", "Aaron Sorkin", "David Schwimmer"), "David Crane", "Entretenimiento", "Medio"),
        QuestionModel("¿En qué serie de televisión se encuentran los personajes Walter White y Jesse Pinkman?", listOf("Breaking Bad", "The Sopranos", "The Wire", "Mad Men"), "Breaking Bad", "Entretenimiento", "Medio"),
        QuestionModel("¿Qué famosa serie de animación presenta a cuatro niños llamados Stan, Kyle, Cartman y Kenny?", listOf("The Simpsons", "Family Guy", "South Park", "Rick and Morty"), "South Park", "Entretenimiento", "Medio"),
        QuestionModel("¿Quién interpretó a Hermione Granger en las películas de 'Harry Potter'?", listOf("Emma Watson", "Emma Stone", "Emma Roberts", "Emma Thompson"), "Emma Watson", "Entretenimiento", "Medio"),
        QuestionModel("¿En qué serie de televisión los personajes luchan por el Trono de Hierro?", listOf("Vikings", "Game of Thrones", "The Tudors", "The Witcher"), "Game of Thrones", "Entretenimiento", "Medio"),
        QuestionModel("¿Cuál es la serie de televisión animada sobre un niño llamado Finn y su perro Jake en la Tierra de Ooo?", listOf("Adventure Time", "Regular Show", "The Amazing World of Gumball", "Steven Universe"), "Adventure Time", "Entretenimiento", "Medio"),
        QuestionModel("¿En qué película el personaje principal busca respuestas en una simulación de realidad virtual llamada 'The Matrix'?", listOf("Inception", "Blade Runner", "The Matrix", "Tron"), "The Matrix", "Entretenimiento", "Medio"),
        QuestionModel("¿Quién interpretó a Jack Dawson en la película 'Titanic'?", listOf("Leonardo DiCaprio", "Johnny Depp", "Brad Pitt", "Tom Cruise"), "Leonardo DiCaprio", "Entretenimiento", "Medio"),
        QuestionModel("¿En qué serie de televisión un grupo de niños se enfrenta a extrañas criaturas en un pueblo llamado Hawkins?", listOf("Stranger Things", "The X-Files", "The Twilight Zone", "Supernatural"), "Stranger Things", "Entretenimiento", "Medio"),
        QuestionModel("¿Cuál es el nombre del famoso director de cine conocido por películas como 'Pulp Fiction' y 'Kill Bill'?", listOf("Quentin Tarantino", "Steven Spielberg", "Martin Scorsese", "Christopher Nolan"), "Quentin Tarantino", "Entretenimiento", "Medio"),
        QuestionModel("¿En qué película de Disney el personaje principal se embarca en un viaje para devolver un anillo?", listOf("Frozen", "Moana", "Brave", "Tangled"), "Moana", "Cine", "Medio"),
        QuestionModel("¿Cuál es el nombre del creador de la serie de televisión 'The Office'?", listOf("Steve Carell", "Ricky Gervais", "John Krasinski", "Greg Daniels"), "Ricky Gervais", "Televisión", "Medio"),
        QuestionModel("¿En qué película el personaje principal se encuentra atrapado en un bucle temporal en el Día de la Marmota?", listOf("Groundhog Day", "Edge of Tomorrow", "Happy Death Day", "Palm Springs"), "Groundhog Day", "Entretenimiento", "Medio"),
        QuestionModel("¿Cuál es la serie de televisión basada en los libros de George R.R. Martin y ambientada en Westeros?", listOf("The Witcher", "Game of Thrones", "Outlander", "The Expanse"), "Game of Thrones", "Entretenimiento", "Medio"),


        //Geografia dificil
        QuestionModel("¿Cuál es el país más extenso del mundo?", listOf("Rusia", "Canadá", "China", "Estados Unidos"), "Rusia", "Geografía", "Difícil"),
        QuestionModel("¿Cuál es la capital más alta del mundo?", listOf("La Paz", "Quito", "Bogotá", "Kathmandú"), "La Paz", "Geografía", "Difícil"),
        QuestionModel("¿En qué océano se encuentra la fosa de las Marianas, el punto más profundo de la Tierra?", listOf("Océano Pacífico", "Océano Atlántico", "Océano Índico", "Océano Antártico"), "Océano Pacífico", "Geografía", "Difícil"),
        QuestionModel("¿Cuál es el río más largo del mundo?", listOf("Amazonas", "Nilo", "Yangtsé", "Misisipi"), "Amazonas", "Geografía", "Difícil"),
        QuestionModel("¿En qué cadena montañosa se encuentra el monte Everest?", listOf("Himalaya", "Andes", "Alpes", "Rocosas"), "Himalaya", "Geografía", "Difícil"),
        QuestionModel("¿Cuál es la ciudad más poblada de África?", listOf("Lagos", "El Cairo", "Kinshasa", "Yakarta"), "Lagos", "Geografía", "Difícil"),
        QuestionModel("¿En qué país se encuentra el desierto de Kalahari?", listOf("Namibia", "Botswana", "Sudáfrica", "Zimbabwe"), "Botswana", "Geografía", "Difícil"),
        QuestionModel("¿Cuál es la capital de Kiribati, un país insular en el Pacífico Central?", listOf("Tarawa", "Majuro", "Funafuti", "Nauru"), "Tarawa", "Geografía", "Difícil"),
        QuestionModel("¿En qué país se encuentra el lago Baikal, el lago más profundo del mundo?", listOf("Rusia", "Mongolia", "China", "Kazajistán"), "Rusia", "Geografía", "Difícil"),
        QuestionModel("¿Cuál es el punto más bajo de la Tierra y en qué mar se encuentra?", listOf("Mar Muerto", "Mariana Trench", "Lago Baikal", "Mar Caspio"), "Mar Muerto", "Geografía", "Difícil"),
        QuestionModel("¿Cuál es el país más pequeño del mundo en términos de área?", listOf("Mónaco", "Vaticano", "Nauru", "San Marino"), "Vaticano", "Geografía", "Difícil"),
        QuestionModel("¿En qué país se encuentra el archipiélago de Svalbard?", listOf("Noruega", "Suecia", "Dinamarca", "Finlandia"), "Noruega", "Geografía", "Difícil"),
        QuestionModel("¿Cuál es el país más grande de América del Sur?", listOf("Brasil", "Argentina", "Colombia", "Perú"), "Brasil", "Geografía", "Difícil"),
        QuestionModel("¿En qué océano se encuentra la isla de Madagascar?", listOf("Océano Índico", "Océano Pacífico", "Océano Atlántico", "Océano Antártico"), "Océano Índico", "Geografía", "Difícil"),
        QuestionModel("¿Cuál es la capital de Bután, un pequeño país en el Himalaya?", listOf("Thimphu", "Paro", "Punakha", "Jakar"), "Thimphu", "Geografía", "Difícil"),
        QuestionModel("¿En qué país se encuentra el golfo de Guinea?", listOf("Nigeria", "Camerún", "Angola", "Ghana"), "Nigeria", "Geografía", "Difícil"),
        QuestionModel("¿Cuál es la isla más grande del mundo?", listOf("Groenlandia", "Borneo", "Madagascar", "Java"), "Groenlandia", "Geografía", "Difícil"),
        QuestionModel("¿En qué país se encuentra el lago Titicaca?", listOf("Perú", "Bolivia", "Chile", "Argentina"), "Bolivia", "Geografía", "Difícil"),
        QuestionModel("¿Cuál es la capital de Mongolia?", listOf("Ulán Bator", "Astana", "Biskek", "Ereván"), "Ulán Bator", "Geografía", "Difícil"),
        QuestionModel("¿En qué continente se encuentra el monte Kilimanjaro?", listOf("África", "Asia", "América del Sur", "Europa"), "África", "Geografía", "Difícil"),


        //Historia dificil
        QuestionModel("¿Cuál fue la principal causa de la Guerra de los Treinta Años?", listOf("Religión", "Territorio", "Economía", "Poder"), "Religión", "Historia", "Difícil"),
        QuestionModel("¿Qué batalla fue un punto de inflexión durante la Segunda Guerra Mundial en el Frente Oriental?", listOf("Batalla de Stalingrado", "Batalla de Midway", "Batalla de El Alamein", "Batalla de las Ardenas"), "Batalla de Stalingrado", "Historia", "Difícil"),
        QuestionModel("¿Quién fue el líder de la Revolución Cultural China en la década de 1960?", listOf("Mao Zedong", "Deng Xiaoping", "Chiang Kai-shek", "Zhou Enlai"), "Mao Zedong", "Historia", "Difícil"),
        QuestionModel("¿En qué año se firmó el Tratado de Versalles al final de la Primera Guerra Mundial?", listOf("1919", "1921", "1923", "1918"), "1919", "Historia", "Difícil"),
        QuestionModel("¿Qué imperio fue conocido como el Imperio Persa Aqueménida y tuvo a Ciro el Grande como uno de sus fundadores?", listOf("Imperio Persa", "Imperio Parto", "Imperio Sasanida", "Imperio Babilónico"), "Imperio Persa", "Historia", "Difícil"),
        QuestionModel("¿En qué año se llevó a cabo la Revolución Gloriosa en Inglaterra?", listOf("1688", "1642", "1750", "1812"), "1688", "Historia", "Difícil"),
        QuestionModel("¿Quién fue el último zar de Rusia antes de la Revolución Rusa de 1917?", listOf("Nicolás II", "Alejandro III", "Pedro el Grande", "Iván el Terrible"), "Nicolás II", "Historia", "Difícil"),
        QuestionModel("¿Cuál fue la dinastía que gobernó China durante la mayor parte del segundo milenio antes de la República?", listOf("Dinastía Qing", "Dinastía Tang", "Dinastía Ming", "Dinastía Han"), "Dinastía Qing", "Historia", "Difícil"),
        QuestionModel("¿Quién fue el líder militar y político de los estados unidos durante la Guerra Civil Americana?", listOf("Abraham Lincoln", "Ulysses S. Grant", "Robert E. Lee", "Jefferson Davis"), "Ulysses S. Grant", "Historia", "Difícil"),
        QuestionModel("¿Cuál fue el evento conocido como la Noche de los Cristales Rotos durante la Alemania nazi?", listOf("Kristallnacht", "Reichstag Fire", "Anschluss", "Operation Barbarossa"), "Kristallnacht", "Historia", "Difícil"),
        QuestionModel("¿Quién fue el emperador romano que legalizó el cristianismo con el Edicto de Milán en el año 313?", listOf("Constantino el Grande", "Diocleciano", "Julio César", "Marco Aurelio"), "Constantino el Grande", "Historia", "Difícil"),
        QuestionModel("¿Cuál fue el conflicto militar que llevó a la independencia de México del dominio español en el siglo XIX?", listOf("Guerra de Independencia Mexicana", "Guerra México-Estados Unidos", "Guerra de Reforma", "Guerra Cristera"), "Guerra de Independencia Mexicana", "Historia", "Difícil"),
        QuestionModel("¿En qué año se estableció la dinastía Ming en China?", listOf("1368", "1420", "1500", "1600"), "1368", "Historia", "Difícil"),
        QuestionModel("¿Quién fue el líder de la Revolución Rusa en octubre de 1917?", listOf("Vladimir Lenin", "Joseph Stalin", "Leon Trotsky", "Nicholas II"), "Vladimir Lenin", "Historia", "Difícil"),
        QuestionModel("¿En qué año se llevó a cabo la Revolución Francesa?", listOf("1789", "1799", "1804", "1815"), "1789", "Historia", "Difícil"),
        QuestionModel("¿Cuál fue la batalla clave que marcó el fin de Napoleón Bonaparte en 1815?", listOf("Batalla de Waterloo", "Batalla de Austerlitz", "Batalla de Leipzig", "Batalla de Borodino"), "Batalla de Waterloo", "Historia", "Difícil"),
        QuestionModel("¿Cuál fue la causa principal de la Guerra de los Siete Años en el siglo XVIII?", listOf("Disputa territorial", "Poder religioso", "Economía colonial", "Sucesión al trono"), "Economía colonial", "Historia", "Difícil"),
        QuestionModel("¿Quién fue el emperador de Japón que renunció a su divinidad después de la Segunda Guerra Mundial?", listOf("Emperador Hirohito", "Emperador Meiji", "Emperador Akihito", "Emperador Taisho"), "Emperador Hirohito", "Historia", "Difícil"),
        QuestionModel("¿Qué líder soviético implementó la política de la Perestroika en la década de 1980?", listOf("Mijaíl Gorbachov", "Leonid Brezhnev", "Nikita Jrushchov", "Josef Stalin"), "Mijaíl Gorbachov", "Historia", "Difícil"),
        QuestionModel("¿En qué año se fundó la Liga de las Naciones después de la Primera Guerra Mundial?", listOf("1920", "1918", "1935", "1945"), "1920", "Historia", "Difícil"),


        //Deportes dificil
        QuestionModel("¿En qué año se celebró la primera Copa Mundial de la FIFA?", listOf("1930", "1926", "1934", "1938"), "1930", "Deportes", "Difícil"),
        QuestionModel("¿Cuál es el único país que ha participado en todas las ediciones de los Juegos Olímpicos modernos desde su inicio en 1896?", listOf("Grecia", "Estados Unidos", "Francia", "Reino Unido"), "Grecia", "Deportes", "Difícil"),
        QuestionModel("¿Cuántas veces ha ganado Rafael Nadal el torneo de Roland Garros hasta 2022?", listOf("13", "11", "9", "7"), "13", "Deportes", "Difícil"),
        QuestionModel("¿En qué año fue la última vez que la selección de fútbol de Italia ganó la Copa Mundial de la FIFA antes de 2022?", listOf("2006", "2010", "2014", "2018"), "2006", "Deportes", "Difícil"),
        QuestionModel("¿Cuántos Grand Slam ha ganado Serena Williams en su carrera hasta 2022?", listOf("23", "20", "18", "16"), "23", "Deportes", "Difícil"),
        QuestionModel("¿Cuál es el nadador más condecorado en la historia de los Juegos Olímpicos con 23 medallas de oro?", listOf("Michael Phelps", "Mark Spitz", "Ian Thorpe", "Ryan Lochte"), "Michael Phelps", "Deportes", "Difícil"),
        QuestionModel("¿Cuántas veces ha ganado Lionel Messi el premio Balón de Oro hasta 2022?", listOf("7", "6", "5", "4"), "7", "Deportes", "Difícil"),
        QuestionModel("¿Cuántas medallas de oro olímpicas ganó el corredor Usain Bolt durante su carrera?", listOf("8", "9", "7", "6"), "8", "Deportes", "Difícil"),
        QuestionModel("¿Cuál es el equipo de rugby que ha ganado más Copas del Mundo de Rugby hasta 2022?", listOf("Nueva Zelanda", "Sudáfrica", "Australia", "Inglaterra"), "Nueva Zelanda", "Deportes", "Difícil"),
        QuestionModel("¿En qué año se celebró por primera vez la Serie Mundial de Béisbol?", listOf("1903", "1910", "1925", "1932"), "1903", "Deportes", "Difícil"),
        QuestionModel("¿Cuántas veces ha ganado la selección de fútbol de Alemania la Eurocopa hasta 2022?", listOf("3", "2", "4", "1"), "3", "Deportes", "Difícil"),
        QuestionModel("¿Cuántos títulos de la NBA ha ganado Michael Jordan en su carrera?", listOf("6", "5", "7", "4"), "6", "Deportes", "Difícil"),
        QuestionModel("¿En qué año se celebró la primera edición de la Copa Davis de tenis?", listOf("1900", "1911", "1923", "1938"), "1900", "Deportes", "Difícil"),
        QuestionModel("¿Quién es el máximo goleador en la historia de la Liga de Campeones de la UEFA hasta 2022?", listOf("Cristiano Ronaldo", "Lionel Messi", "Raúl González", "Robert Lewandowski"), "Cristiano Ronaldo", "Deportes", "Difícil"),
        QuestionModel("¿Cuál es el país que ha ganado más medallas en los Juegos Olímpicos de Invierno hasta 2022?", listOf("Noruega", "Estados Unidos", "Alemania", "Rusia"), "Noruega", "Deportes", "Difícil"),
        QuestionModel("¿En qué año se introdujo por primera vez el ciclismo en los Juegos Olímpicos?", listOf("1896", "1904", "1920", "1932"), "1896", "Deportes", "Difícil"),
        QuestionModel("¿Quién fue el primer jugador de la NBA en promediar un triple-doble en una temporada?", listOf("Oscar Robertson", "Magic Johnson", "LeBron James", "Russell Westbrook"), "Oscar Robertson", "Deportes", "Difícil"),
        QuestionModel("¿Cuál es el único país sudamericano que ha ganado la Copa Mundial de Rugby?", listOf("Argentina", "Brasil", "Uruguay", "Chile"), "Argentina", "Deportes", "Difícil"),
        QuestionModel("¿Cuántas veces ha ganado el equipo de cricket de Australia la Copa del Mundo hasta 2022?", listOf("5", "4", "6", "3"), "5", "Deportes", "Difícil"),
        QuestionModel("¿En qué año se celebraron los primeros Juegos Olímpicos modernos?", listOf("1896", "1900", "1904", "1912"), "1896", "Deportes", "Difícil"),

        //Arte y literatura dificil

        QuestionModel("¿Cuál es la novela de Fyodor Dostoevsky que explora temas de moralidad, libre albedrío y culpa?", listOf("Crimen y castigo", "Los hermanos Karamázov", "El idiota", "Los demonios"), "Crimen y castigo", "Arte y literatura", "Difícil"),
        QuestionModel("¿En qué movimiento artístico se encuentra la obra 'Guernica' de Pablo Picasso?", listOf("Cubismo", "Surrealismo", "Impresionismo", "Expresionismo"), "Cubismo", "Arte y literatura", "Difícil"),
        QuestionModel("¿Quién escribió la obra de teatro 'Esperando a Godot'?", listOf("Samuel Beckett", "Eugene O'Neill", "Harold Pinter", "Tom Stoppard"), "Samuel Beckett", "Arte y literatura", "Difícil"),
        QuestionModel("¿Cuál es el nombre del movimiento artístico caracterizado por formas geométricas y colores primarios?", listOf("De Stijl", "Fauvismo", "Cubismo", "Surrealismo"), "De Stijl", "Arte y literatura", "Difícil"),
        QuestionModel("¿Quién escribió la novela 'Cien años de soledad'?", listOf("Gabriel García Márquez", "Mario Vargas Llosa", "Julio Cortázar", "Isabel Allende"), "Gabriel García Márquez", "Arte y literatura", "Difícil"),
        QuestionModel("¿Quién es conocido por sus esculturas del David y La Piedad?", listOf("Michelangelo Buonarroti", "Leonardo da Vinci", "Donatello", "Raphael Sanzio"), "Michelangelo Buonarroti", "Arte y literatura", "Difícil"),
        QuestionModel("¿En qué movimiento artístico se encuentra la obra 'La persistencia de la memoria' de Salvador Dalí?", listOf("Surrealismo", "Cubismo", "Impresionismo", "Expresionismo"), "Surrealismo", "Arte y literatura", "Difícil"),
        QuestionModel("¿Quién es el autor de la obra teatral 'Romeo y Julieta'?", listOf("William Shakespeare", "Christopher Marlowe", "Ben Jonson", "John Milton"), "William Shakespeare", "Arte y literatura", "Difícil"),
        QuestionModel("¿En qué movimiento artístico se encuentra la obra 'El grito' de Edvard Munch?", listOf("Expresionismo", "Cubismo", "Impresionismo", "Surrealismo"), "Expresionismo", "Arte y literatura", "Difícil"),
        QuestionModel("¿Quién escribió 'Matar a un ruiseñor'?", listOf("Harper Lee", "John Steinbeck", "Mark Twain", "J.D. Salinger"), "Harper Lee", "Arte y literatura", "Difícil"),
        QuestionModel("¿Cuál es el nombre de la corriente artística que se caracteriza por la representación de la luz y el color de manera fragmentada?", listOf("Impresionismo", "Cubismo", "Fauvismo", "Realismo"), "Impresionismo", "Arte y literatura", "Difícil"),
        QuestionModel("¿Quién es el autor de la novela 'Mujer en punto cero'?", listOf("Nawal El Saadawi", "Naguib Mahfouz", "Khaled Hosseini", "Tayeb Salih"), "Nawal El Saadawi", "Arte y literatura", "Difícil"),
        QuestionModel("¿En qué movimiento artístico se encuentra la obra 'Noche estrellada' de Vincent van Gogh?", listOf("Postimpresionismo", "Cubismo", "Surrealismo", "Fauvismo"), "Postimpresionismo", "Arte y literatura", "Difícil"),
        QuestionModel("¿Quién escribió 'El retrato de Dorian Gray'?", listOf("Oscar Wilde", "Edgar Allan Poe", "Jane Austen", "F. Scott Fitzgerald"), "Oscar Wilde", "Arte y literatura", "Difícil"),
        QuestionModel("¿En qué país nació el pintor abstracto Wassily Kandinsky?", listOf("Rusia", "Francia", "Alemania", "Estados Unidos"), "Rusia", "Arte", "Difícil"),
        QuestionModel("¿Quién es el autor de la novela 'El extranjero'?", listOf("Albert Camus", "Franz Kafka", "Jean-Paul Sartre", "Fyodor Dostoevsky"), "Albert Camus", "Arte y literatura", "Difícil"),
        QuestionModel("¿En qué movimiento artístico se encuentra la obra 'Las señoritas de Avignon' de Pablo Picasso?", listOf("Cubismo", "Surrealismo", "Expresionismo", "Fauvismo"), "Cubismo", "Arte y literatura", "Difícil"),
        QuestionModel("¿Cuál es el nombre del movimiento literario y artístico que surgió en México a principios del siglo XX y buscaba una identidad nacional?", listOf("Modernismo", "Realismo Mágico", "Generación del 27", "Estridentismo"), "Estridentismo", "Arte y literatura", "Difícil"),
        QuestionModel("¿Quién escribió la novela 'Crimen y Castigo'?", listOf("Fyodor Dostoevsky", "Leo Tolstoy", "Anton Chekhov", "Ivan Turgenev"), "Fyodor Dostoevsky", "Arte y literatura", "Difícil"),
        QuestionModel("¿En qué movimiento artístico se encuentra la obra 'El jardín de las delicias' de Hieronymus Bosch?", listOf("Renacimiento", "Manierismo", "Gótico", "Barroco"), "Gótico", "Arte y literatura", "Difícil"),

        //Entretenimiento dificil
        QuestionModel("¿Cuál es la película de ciencia ficción dirigida por Andrei Tarkovsky que se basa en la novela 'Solaris' de Stanisław Lem?", listOf("Solaris", "Stalker", "Andrei Rublev", "Mirror"), "Solaris", "Entretenimiento", "Difícil"),
        QuestionModel("¿Cuál es el nombre del primer videojuego de rol creado por Hironobu Sakaguchi y lanzado por Square en 1987?", listOf("Final Fantasy", "Dragon Quest", "Chrono Trigger", "The Legend of Zelda"), "Final Fantasy", "Entretenimiento", "Difícil"),
        QuestionModel("¿Qué serie de televisión británica creada por Charlie Brooker explora historias de ciencia ficción y tecnología distópica?", listOf("Black Mirror", "The Twilight Zone", "Westworld", "Stranger Things"), "Black Mirror", "Entretenimiento", "Difícil"),
        QuestionModel("¿Quién fue el director de la película surrealista 'El Topo', lanzada en 1970?", listOf("Alejandro Jodorowsky", "David Lynch", "Luis Buñuel", "Federico Fellini"), "Alejandro Jodorowsky", "Entretenimiento", "Difícil"),
        QuestionModel("¿Cuál es el nombre del famoso juego de cartas coleccionables lanzado por Wizards of the Coast en 1993?", listOf("Magic: The Gathering", "Yu-Gi-Oh!", "Pokemon TCG", "Duel Masters"), "Magic: The Gathering", "Entretenimiento", "Difícil"),
        QuestionModel("¿Quién es el creador y director de la serie de animación 'BoJack Horseman'?", listOf("Raphael Bob-Waksberg", "Dan Harmon", "Seth MacFarlane", "Mike Judge"), "Raphael Bob-Waksberg", "Entretenimiento", "Difícil"),
        QuestionModel("¿Cuál es el nombre del grupo musical noruego conocido por su estilo de black metal y por quemar iglesias en la década de 1990?", listOf("Mayhem", "Burzum", "Darkthrone", "Emperor"), "Mayhem", "Entretenimiento", "Difícil"),
        QuestionModel("¿En qué año se lanzó el videojuego 'Metal Gear Solid' para la consola PlayStation?", listOf("1998", "1996", "1994", "2000"), "1998", "Entretenimiento", "Difícil"),
        QuestionModel("¿Cuál es el nombre de la película dirigida por Darren Aronofsky que explora la obsesión con el ballet y la rivalidad entre bailarinas?", listOf("Cisne Negro", "Requiem for a Dream", "El Luchador", "The Fountain"), "Cisne Negro", "Entretenimiento", "Difícil"),
        QuestionModel("¿Qué director estadounidense es conocido por películas como 'Mulholland Drive' y 'Blue Velvet'?", listOf("David Lynch", "Quentin Tarantino", "Martin Scorsese", "Coen Brothers"), "David Lynch", "Entretenimiento", "Difícil"),
        QuestionModel("¿Cuál es el nombre del creador y escritor de la serie de televisión 'The Leftovers'?", listOf("Damon Lindelof", "J.J. Abrams", "Matthew Weiner", "Vince Gilligan"), "Damon Lindelof", "Entretenimiento", "Difícil"),
        QuestionModel("¿En qué año se lanzó la novela gráfica 'Maus' de Art Spiegelman, que aborda la narrativa del Holocausto utilizando animales antropomórficos?", listOf("1986", "1992", "1979", "2004"), "1986", "Entretenimiento", "Difícil"),
        QuestionModel("¿Quién es el director de la película de ciencia ficción 'Blade Runner', lanzada en 1982?", listOf("Ridley Scott", "Steven Spielberg", "James Cameron", "George Lucas"), "Ridley Scott", "Entretenimiento", "Difícil"),
        QuestionModel("¿Cuál es el nombre del videojuego independiente lanzado en 2012, desarrollado por Jonathan Blow, conocido por su enfoque en rompecabezas y narrativa?", listOf("Braid", "Limbo", "Fez", "The Witness"), "The Witness", "Entretenimiento", "Difícil"),
        QuestionModel("¿Quién es el autor de la novela de ciencia ficción 'Neuromante', que popularizó el término 'ciberespacio'?", listOf("William Gibson", "Philip K. Dick", "Isaac Asimov", "Arthur C. Clarke"), "William Gibson", "Entretenimiento", "Difícil"),
        QuestionModel("¿En qué año se estrenó la película animada japonesa 'Akira', dirigida por Katsuhiro Otomo?", listOf("1988", "1995", "2001", "1992"), "1988", "Entretenimiento", "Difícil"),
        QuestionModel("¿Cuál es el nombre del creador de la serie de televisión 'Twin Peaks'?", listOf("David Lynch", "Mark Frost", "J.J. Abrams", "Matthew Weiner"), "David Lynch", "Entretenimiento", "Difícil"),
        QuestionModel("¿Qué banda de rock experimental y progresivo lanzó el álbum 'OK Computer' en 1997?", listOf("Radiohead", "Pink Floyd", "Tool", "Nine Inch Nails"), "Radiohead", "Entretenimiento", "Difícil"),
        QuestionModel("¿Cuál es el título de la serie de libros de ciencia ficción escrita por Isaac Asimov, que aborda la historia de la humanidad en un futuro lejano?", listOf("Fundación", "Dune", "Hyperion", "Ender's Game"), "Fundación", "Entretenimiento", "Difícil"),
        QuestionModel("¿Cuál es el nombre del director y guionista francés conocido por películas como 'Amélie' y 'Delicatessen'?", listOf("Jean-Pierre Jeunet", "François Truffaut", "Claude Chabrol", "Luc Besson"), "Jean-Pierre Jeunet", "Entretenimiento", "Difícil"),




    )
}